# curl --request POST
#--url 'http://localhost:8080/api/rest/v10/employees?page=0&max=20'
#--header 'Authorization: Basic dHVyZ2F5OnRjMTIzNA=='
#--header 'Content-Type: application/json'
#--data '{
#"email":"turgay.can2@inomera.com",
#"fullname":"Turgay Can",
#"title":"Software Engineer"
#}'

POST http://localhost:8080/api/rest/v10/employees?page=0&max=20
Authorization: Basic dHVyZ2F5OnRjMTIzNA==
Content-Type: application/json

{
  "email": "turgay.can2@inomera.com",
  "fullname": "Turgay Can",
  "title": "Software Engineer"
}

###

